import { Routes } from '@angular/router';

// No component imports needed - app.component handles all rendering via ViewState

export const routes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'home', children: [] },
  { path: 'login', children: [] },
  { path: 'register', children: [] },
  { path: 'privacy-policy', children: [] },
  { path: 'child-safety-policy', children: [] },
  { path: 'about-us', children: [] },
  { path: 'blog', children: [] },
  { path: 'contact-detail', children: [] },
  { path: 'terms-and-conditions', children: [] },
  { path: 'success-stories', children: [] },
  { path: 'delete-account', children: [] },
  { path: 'dashboard', children: [] },
  { path: 'settings', children: [] },
  { path: 'messages', children: [] },
  { path: 'favorites', children: [] },
  { path: 'notifications', children: [] },
  { path: 'welcome', children: [] },
  { path: 'email-otp', children: [] },
  { path: 'set-password', children: [] },
  { path: 'profile-form', children: [] },
  { path: 'edit-profile', children: [] },
  { path: 'partner-preferences', children: [] },
  { path: 'photo-gallery', children: [] },
  { path: 'marriage-profile-pdf', children: [] },
  { path: 'biodata-maker', children: [] },
  { path: 'chat-detail', children: [] },
  { path: 'profile-detail', children: [] },
  { path: 'notification-settings', children: [] },
  { path: 'change-password', children: [] },
  { path: 'forgot-password', children: [] },
  { path: 'premium', children: [] },
  { path: 'privacy-settings', children: [] },
  { path: 'reported-blocked-users', children: [] },
  { path: 'shortlisted', children: [] },
  { path: 'my-connections', children: [] },
  { path: 'community', children: [] },
  { path: 'community-events', children: [] },
  { path: 'event-detail', children: [] },
  { path: 'teachings', children: [] },
  { path: 'teaching-article', children: [] },
  { path: 'language', children: [] },
  { path: 'faq', children: [] },
  { path: 'help-center', children: [] },
  { path: '**', redirectTo: '/home' }
];