// ViewState type definition for app navigation
export type Language = 'en' | 'hi' | 'mr'; // adjust the language codes as needed

// export type ViewState = 'home' | 'about' | 'contact'; // adjust based on your views

// ...existing code...
export type ViewState =
  | 'home'
  | 'login'
  | 'register'
  | 'email-otp'
  | 'set-password'
  | 'profile-form'
  | 'partner-preferences'
  | 'photo-gallery'
  | 'marriage-profile-pdf'
  | 'biodata-maker'
  | 'welcome'
  | 'dashboard'
  | 'settings'
  | 'notification-settings'
  | 'change-password'
  | 'privacy-settings'
  | 'reported-blocked-users'
  | 'language'
  | 'messages'
  | 'chat-detail'
  | 'favorites'
  | 'premium'
  | 'profile-detail'
  | 'notifications'
  | 'privacy-policy'
  | 'child-safety-policy'
  | 'contact-detail'
  | 'terms-and-conditions'
  | 'about-us'
  | 'blog'
  | 'success-stories'
  | 'delete-account'
  | 'edit-profile'
  | 'help-center'
  | 'help-support'
  | 'forgot-password'
  | 'shortlisted'
  | 'my-connections'
  | 'community'
  | 'community-events'
  | 'event-detail'
  | 'teachings'
  | 'teaching-article';